[#176299519] azure pipeline fix check file deleted

diff --git a/.devops/code-review.yml b/.devops/code-review.yml
--- a/.devops/code-review.yml
+++ b/.devops/code-review.yml
@@ -49,15 +49,25 @@ jobs:
             export ARM_SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)
             export ARM_TENANT_ID=$(TENANT_ID)
 
+            # task output status code
+            output_status_code=0
+
+            checkerror() {
+              # parameters:
+              # $1: status code of the last command.
+              # $2: terragrunt module path.
+              if [[ $1 -ne 0 ]]; then
+                echo -e "${RED}$2 plan failed${NC}"
+                output_status_code=1
+              fi
+            }
+
             base_dir=$(pwd)
             current_branch=${GIT_BRANCH}
             echo "Current branch ${current_branch}"
 
             # Get new files or changed in the current branch
             file_changed=$(git diff --diff-filter=AM --name-only origin/master | grep terragrunt.hcl)
-
-            # task output status code
-            output_status_code=0
 
             for item in ${file_changed}
             do
@@ -71,34 +81,26 @@ jobs:
 
               # if plan fails and output_status_code is 0
               # set output_status_code to 1 (error)
-              if [[ $? -ne 0 ]]; then
-                echo -e "${RED}${wdir} plan failed${NC}"
-                if [[ ${output_status_code} -eq 0 ]]; then
-                  output_status_code=1
-                fi
-              fi
+              checkerror $? ${item}
             done
 
             # get file deleted in the current branch.
             file_deleted=$(git diff --diff-filter=D --name-only origin/master | grep terragrunt.hcl)
 
-            if [ -z ${file_deleted} ]; then
+            if [ ${#file_deleted} eq 0 ]; then
               git fetch
               git checkout master
             fi
 
             for item in ${file_deleted}
             do
-              echo "Deleted file: ${item}."
+              cd ${base_dir}
+              wdir=$(dirname $item)
+              echo "Processing ${item}"
+
+              cd ${wdir}
               terragrunt plan -destroy
-
-              if [[ $? -ne 0 ]]; then
-                echo -e "${RED}${wdir} plan failed${NC}"
-                if [[ ${output_status_code} -eq 0 ]]; then
-                  output_status_code=1
-                fi
-              fi
-
+              checkerror $? ${item}
             done
 
             exit ${output_status_code}
