[#176697062] Web test appbackendl* (#424)
* [#176697062] first draft web test appbackendli

* [#176697062] ip restriction to allow application insights to call appbackendli

* [#176697062] web tests for app backends

* [#176697062] test: remove ping.xml file

* [#176697062] removed ping.xml files: they are already included within the module

* [#176697062] moved all app insights ips in a shared configuration file

* [#176697062] changed plan pipeline to exclude *vars.hcl files

* [#176697062] plan pipeline excludes config files *vars.hcl

* [#176697062] plan pipeline excludes config files *vars.hcl fix condition

* [#176697062] plan pipeline excludes config files *vars.hcl fix condition

diff --git a/.devops/plan-pipeline.yaml b/.devops/plan-pipeline.yaml
--- a/.devops/plan-pipeline.yaml
+++ b/.devops/plan-pipeline.yaml
@@ -87,16 +87,21 @@ jobs:
             for item in ${file_changed}
             do
               cd ${base_dir}
+              # get working dir ... where to run the apply.
               wdir=$(dirname $item)
 
               echo "Processing ${item}"
 
-              cd ${wdir}
-              terragrunt plan
+              # do not check config files.
+              if ! [[ ${item} =~ "vars.hcl" ]]; then
+                cd ${wdir}
+                terragrunt plan
 
-              # if plan fails and output_status_code is 0
-              # set output_status_code to 1 (error)
-              checkerror $? ${item}
+                # if plan fails and output_status_code is 0
+                # set output_status_code to 1 (error)
+                checkerror $? ${item}
+              fi
+
             done
 
             # get file deleted in the current branch.
